spring.application.name=servicioAgregador
server.port=8083
url.fuente.estatica=localhost:8080/fuenteEstatica
url.fuente.dinamica=localhost:8081/fuenteDinamica
url.fuente.proxy=localhost:8082/fuenteProxy